api_token: "YOUR_API_KEY"
api_endpoint: "https://api.xdr.trendmicro.com/v3.0/search/detections"
start_date: "2024-10-20T00:00:00Z"
end_date: "2024-10-31T23:59:59Z"
max_results: 1000000
results_per_call: 5000
query_filter: "productCode:PTP AND act:Block"
output_file: "detections.csv"
checkpoint_file: "checkpoint.json"
num_threads: 5
request_timeout: 60
rate_limit_per_second: 5
rate_limit_minute: 20
rate_limit_hour: 800
